import os
import json
import glob
import random
import re
from datasets import load_dataset

def get_blacklisted_ids(base_dir, ds_key):
    """
    Reads all N*.jsonl files and extracts the 'id' to prevent data leakage.
    Using 'id' is safer than 'row_idx' for RAFT because indices reset per task.
    """
    used_ids = set()
    ds_dir = os.path.join(base_dir, ds_key)
    if not os.path.exists(ds_dir):
        return used_ids
        
    # Look for any N-shot split files generated by make_splits.py
    for file_path in glob.glob(os.path.join(ds_dir, "N*.jsonl")):
        with open(file_path, 'r', encoding='utf-8') as f:
            for line in f:
                try:
                    data = json.loads(line)
                    if "id" in data:
                        used_ids.add(data["id"])
                except:
                    continue
    return used_ids

def verify_no_leakage(base_dir, ds_keys):
    """
    Final safety check: Cross-references all test_50.jsonl files against 
    all N*.jsonl files. Raises error if any overlap is found.
    """
    print("\n" + "="*40)
    print("RUNNING FINAL DATA LEAK-CHECK...")
    print("="*40)
    
    for ds in ds_keys:
        ds_path = os.path.join(base_dir, ds)
        if not os.path.exists(ds_path): 
            print(f"  [?] {ds}: No local training splits found. Skipping check.")
            continue
        
        # 1. Collect all IDs used in Few-Shot Contexts (Training)
        training_ids = set()
        for f in glob.glob(os.path.join(ds_path, "N*.jsonl")):
            with open(f, 'r', encoding='utf-8') as src:
                for line in src:
                    training_ids.add(json.loads(line)["id"])
        
        # 2. Collect all IDs used in the Test Set
        test_file = os.path.join(ds_path, "test_50.jsonl")
        if not os.path.exists(test_file): continue
        
        test_ids = set()
        with open(test_file, 'r', encoding='utf-8') as src:
            for line in src:
                test_ids.add(json.loads(line)["id"])
        
        # 3. Check for Intersection
        overlap = training_ids.intersection(test_ids)
        if overlap:
            raise RuntimeError(f"!!! DATA LEAK DETECTED in {ds} !!!\nOverlapping IDs: {overlap}")
        else:
            print(f"  [v] {ds}: PASS (Checked {len(test_ids)} test vs {len(training_ids)} context IDs)")

def main():
    # Configuration
    RAFT_KEY = "raft" 
    base_dir = "data/splits_out"
    TEST_SEED = 42 # Ensures deterministic 50-sample selection
    
    configs = {
        "gsm8k": {"path": "openai/gsm8k", "name": "main", "split": "test", "is_train": False},
        "superglue_boolq": {"path": "super_glue", "name": "boolq", "split": "validation", "is_train": False},
        "superglue_rte": {"path": "super_glue", "name": "rte", "split": "validation", "is_train": False},
        "financial_phrasebank": {"path": "financial_phrasebank", "name": "sentences_allagree", "split": "train", "is_train": True},
        "ifbench": {"path": "google/IFEval", "name": None, "split": "train", "is_train": True},
    }

    # --- PART 1: PROCESS STANDARD DATASETS ---
    for ds_key, cfg in configs.items():
        print(f"Building seeded test set for {ds_key}...")
        try:
            if cfg["name"]:
                ds = load_dataset(cfg["path"], cfg["name"], split=cfg["split"], trust_remote_code=True)
            else:
                ds = load_dataset(cfg["path"], split=cfg["split"], trust_remote_code=True)
            
            blacklist = get_blacklisted_ids(base_dir, ds_key)
            candidates = []
            
            for idx, row in enumerate(ds):
                current_id = f"{ds_key}_test_{idx}"
                if current_id in blacklist or str(idx) in blacklist:
                    continue
                
                x_val, y_val = "", ""
                if ds_key == "gsm8k":
                    x_val = f"Question: {row['question']}\nAnswer: Let's think step by step. Return the final answer after ####.\n"
                    y_val = row["answer"].split("####")[-1].strip()
                elif ds_key == "superglue_boolq":
                    x_val = f"Passage: {row['passage']}\nQuestion: {row['question']}\nAnswer (True or False): "
                    y_val = "True" if row["label"] == 1 else "False"
                elif ds_key == "superglue_rte":
                    x_val = f"Premise: {row['premise']}\nHypothesis: {row['hypothesis']}\nAnswer (entailment or not_entailment): "
                    y_val = "not_entailment" if row["label"] == 1 else "entailment"
                elif ds_key == "financial_phrasebank":
                    x_val = f"Sentence: {row['sentence']}\nSentiment classification (0=negative, 1=neutral, 2=positive): Label "
                    y_val = {0: "negative", 1: "neutral", 2: "positive"}.get(row["label"], str(row["label"]))
                elif ds_key == "ifbench":
                    prompt = row.get("prompt", row.get("instruction", ""))
                    x_val = f"Instruction: {prompt}\nResponse: "
                    y_val = ""

                candidates.append({"id": current_id, "x": x_val, "y": y_val, "meta": {"row_idx": idx}})

            # Shuffle candidates with the fixed seed for deterministic sampling
            random.seed(TEST_SEED)
            random.shuffle(candidates)
            test_samples = candidates[:50]

            out_dir = os.path.join(base_dir, ds_key)
            os.makedirs(out_dir, exist_ok=True)
            with open(os.path.join(out_dir, "test_50.jsonl"), "w", encoding="utf-8") as f:
                for s in test_samples:
                    f.write(json.dumps(s, ensure_ascii=False) + "\n")
            print(f"  -> Saved {len(test_samples)} seeded samples to {ds_key}/test_50.jsonl")
            
        except Exception as e:
            print(f"  -> [ERROR] Failed processing {ds_key}: {e}")

    # --- PART 2: PROCESS RAFT (MULTI-TASK SEEDED) ---
    print(f"\nBuilding multi-task test set for {RAFT_KEY}...")
    raft_tasks = [
        'ade_corpus_v2', 'banking_77', 'neurips_impact_statement_risks', 
        'one_stop_english', 'overruling', 'semiconductor_org_types', 
        'systematic_review_inclusion', 'tai_safety_research', 'terms_of_service', 
        'tweet_eval_hate', 'twitter_complaints'
    ]
    blacklist = get_blacklisted_ids(base_dir, RAFT_KEY)
    all_raft_candidates = []

    for task in raft_tasks:
        try:
            ds = load_dataset("ought/raft", task, split="train", trust_remote_code=True)
            for idx, row in enumerate(ds):
                # RAFT Adapter ID format matching src/adapters/raft.py
                stable_id = f"raft_{task}_train_{idx:06d}"
                if stable_id not in blacklist:
                    all_raft_candidates.append({"id": stable_id, "task": task, "row": row, "idx": idx})
        except Exception as e:
            print(f"  -> [Skip] Task {task} failed: {e}")

    if all_raft_candidates:
        random.seed(TEST_SEED)
        random.shuffle(all_raft_candidates)
        
        raft_out_dir = os.path.join(base_dir, RAFT_KEY)
        os.makedirs(raft_out_dir, exist_ok=True)
        
        with open(os.path.join(raft_out_dir, "test_50.jsonl"), "w", encoding="utf-8") as f:
            for item in all_raft_candidates[:50]:
                row = item["row"]
                text_field = next((k for k in ["Sentence", "text", "instruction", "query"] if k in row), list(row.keys())[0])
                
                json_obj = {
                    "id": item["id"],
                    "x": f"Task: {item['task']}\nInput: {row[text_field]}\nLabel: ",
                    "y": str(row["Label"]),
                    "meta": {"dataset": "raft", "task": item["task"], "row_idx": item["idx"]}
                }
                f.write(json.dumps(json_obj, ensure_ascii=False) + "\n")
        print(f"  -> SUCCESS: Saved seeded RAFT samples to {RAFT_KEY}/test_50.jsonl")

    # --- PART 3: FINAL VALIDATION ---
    ds_list = list(configs.keys()) + [RAFT_KEY]
    verify_no_leakage(base_dir, ds_list)

if __name__ == "__main__":
    main()